### ISSUE TITLE
Undeploying an App Engine module can cause an error

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#599] opened 2016-04-06 13:10 UTC
System: Windows 10
IJ version: 2016.1.1
Steps taken:

1) Checkout a war project
2) Configure for App Engine Flex
3) Deploy
4) Undeploy

observed:

Editor is already disposed
--------------Creation trace: 
java.lang.Throwable
	at com.intellij.openapi.util.TraceableDisposable.<init>(TraceableDisposable.java:41)
	at com.intellij.openapi.editor.impl.EditorImpl.<init>(EditorImpl.java:145)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:193)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createViewer(EditorFactoryImpl.java:174)
	at com.intellij.execution.impl.ConsoleViewUtil.setupConsoleEditor(ConsoleViewUtil.java:63)
	at com.intellij.execution.impl.ConsoleViewImpl.doCreateConsoleEditor(ConsoleViewImpl.java:1001)
	at com.intellij.execution.impl.ConsoleViewImpl$15.compute(ConsoleViewImpl.java:942)
	at com.intellij.execution.impl.ConsoleViewImpl$15.compute(ConsoleViewImpl.java:939)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:962)
	at com.intellij.execution.impl.ConsoleViewImpl.createConsoleEditor(ConsoleViewImpl.java:939)
	at com.intellij.execution.impl.ConsoleViewImpl.initConsoleEditor(ConsoleViewImpl.java:524)
	at com.intellij.execution.impl.ConsoleViewImpl.getComponent(ConsoleViewImpl.java:503)
	at com.intellij.remoteServer.impl.runtime.ui.tree.ServersTreeStructure$DeploymentNodeImpl.getComponent(ServersTreeStructure.java:380)
	at com.intellij.remoteServer.impl.runtime.ui.ServersToolWindowContent.onSelectionChanged(ServersToolWindowContent.java:173)
	at com.intellij.remoteServer.impl.runtime.ui.ServersToolWindowContent.access$000(ServersToolWindowContent.java:49)
	at com.intellij.remoteServer.impl.runtime.ui.ServersToolWindowContent$1.valueChanged(ServersToolWindowContent.java:106)
	at javax.swing.JTree.fireValueChanged(JTree.java:2927)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3391)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:643)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.JTree.setSelectionPaths(JTree.java:1647)
	at javax.swing.JTree.setSelectionRows(JTree.java:1729)
	at javax.swing.JTree.setSelectionRow(JTree.java:1704)
	at com.intellij.util.ui.tree.TreeUtil$1.run(TreeUtil.java:516)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:567)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:459)
	at com.intellij.ide.util.treeView.AbstractTreeUi$72.perform(AbstractTreeUi.java:4103)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4354)
	at com.intellij.ide.util.treeView.AbstractTreeUi.selectVisible(AbstractTreeUi.java:4100)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$8100(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$68$1.perform(AbstractTreeUi.java:4015)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4354)
	at com.intellij.ide.util.treeView.AbstractTreeUi.checkPathAndMaybeRevalidate(AbstractTreeUi.java:4026)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$8700(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$68.perform(AbstractTreeUi.java:4012)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4354)
	at com.intellij.ide.util.treeView.AbstractTreeUi._expand(AbstractTreeUi.java:4426)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doSelect(AbstractTreeUi.java:4020)
	at com.intellij.ide.util.treeView.AbstractTreeUi.addNext(AbstractTreeUi.java:3980)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$8500(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$65.perform(AbstractTreeUi.java:3869)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runDone(AbstractTreeUi.java:4354)
	at com.intellij.ide.util.treeView.AbstractTreeUi._select(AbstractTreeUi.java:3820)
	at com.intellij.ide.util.treeView.SelectionRequest.execute(SelectionRequest.java:49)
	at com.intellij.ide.util.treeView.AbstractTreeUpdater$5.run(AbstractTreeUpdater.java:390)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue$3.run(MergingUpdateQueue.java:267)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2405)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:279)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:234)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:378)
	at com.intellij.util.Alarm$Request.run(Alarm.java:389)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:227)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
--------------Kill trace: 
java.lang.Throwable
	at com.intellij.openapi.util.TraceableDisposable.kill(TraceableDisposable.java:46)
	at com.intellij.openapi.editor.impl.EditorImpl.release(EditorImpl.java:883)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.releaseEditor(EditorFactoryImpl.java:212)
	at com.intellij.execution.impl.ConsoleViewImpl$8.run(ConsoleViewImpl.java:614)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
-------------Own trace:
com.intellij.openapi.util.TraceableDisposable$DisposalException: Editor is already disposed
	at com.intellij.openapi.util.TraceableDisposable.throwDisposalError(TraceableDisposable.java:83)
	at com.intellij.openapi.editor.impl.EditorImpl.throwDisposalError(EditorImpl.java:875)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.checkDisposed(TextLayoutCache.java:167)
	at com.intellij.openapi.editor.impl.view.TextLayoutCache.getLineLayout(TextLayoutCache.java:131)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.setFragmentIterator(VisualLineFragmentsIterator.java:159)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.init(VisualLineFragmentsIterator.java:150)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.<init>(VisualLineFragmentsIterator.java:102)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator.<init>(VisualLineFragmentsIterator.java:37)
	at com.intellij.openapi.editor.impl.view.VisualLineFragmentsIterator$1.iterator(VisualLineFragmentsIterator.java:43)
	at com.intellij.openapi.editor.impl.view.EditorCoordinateMapper.xyToVisualPosition(EditorCoordinateMapper.java:246)
	at com.intellij.openapi.editor.impl.view.EditorView.xyToVisualPosition(EditorView.java:181)
	at com.intellij.openapi.editor.impl.EditorImpl.xyToVisualPosition(EditorImpl.java:1283)
	at com.intellij.openapi.editor.impl.EditorImpl.xyToLogicalPosition(EditorImpl.java:1550)
	at com.intellij.openapi.editor.impl.EditorGutterComponentImpl.paint(EditorGutterComponentImpl.java:278)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JViewport.paint(JViewport.java:728)
	at com.intellij.ui.components.JBViewport.paint(JBViewport.java:165)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JLayeredPane.paint(JLayeredPane.java:586)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintChildren(JComponent.java:889)
	at javax.swing.JComponent.paint(JComponent.java:1065)
	at javax.swing.JComponent.paintToOffscreen(JComponent.java:5210)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1579)
	at javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1502)
	at javax.swing.RepaintManager.paint(RepaintManager.java:1272)
	at javax.swing.JComponent._paintImmediately(JComponent.java:5158)
	at javax.swing.JComponent.paintImmediately(JComponent.java:4969)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:831)
	at javax.swing.RepaintManager$4.run(RepaintManager.java:814)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:814)
	at javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:789)
	at javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:738)
	at javax.swing.RepaintManager.access$1200(RepaintManager.java:64)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1732)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:792)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1661)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1610)
	at com.intellij.openapi.ui.Messages$MessageDialog.show(Messages.java:1466)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:272)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:284)
	at com.intellij.openapi.ui.Messages.showDialog(Messages.java:295)
	at com.intellij.openapi.ui.Messages.showMessageDialog(Messages.java:343)
	at com.google.cloud.tools.intellij.appengine.cloud.AppEngineStopAction$StopModuleProcessListener$1.run(AppEngineStopAction.java:94)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by meltsufin** [comment] 2016-04-06 13:20
It looks like another "disposed" issue, potentially related to #577.
Is this only happening on Windows 10?

**Comment by chanseokoh** [comment] 2016-04-06 16:30
#577 seems like a project is disposed, and this one seems like an editor window is disposed.

**Comment by etanshaul** [comment] 2016-04-07 20:25
I suspect this is new to 2016.1. I tried in both 2016 and 15.0.3 and only saw this in the former.

**Comment by patflynn** [comment] 2016-04-12 19:07
@meltsufin does your project close handler thing fix this?

**Comment by etanshaul** [comment] 2016-04-12 19:12
This is unrelated to closing the project. This happens in IJ 2016+ when you undeploy the project after a successful deploy.

The problem is with the addition of the information dialog that tells the user that the stop was successful. I was looking into this but haven't yet determined how to address it.

**Comment by etanshaul** [comment] 2016-04-12 20:51
Update: turns out this has nothing to do with the information dialog. This happens (off and on) when calling UndeploymentTaskCallback#succeeded(). It appears to be a subtle platform bug and I am still trying to get some better details so I can file with JetBrains if needed.

**Comment by patflynn** [comment] 2016-04-14 20:14
if you file this with jetbrains please include a link here and close.

**Comment by etanshaul** [comment] 2016-04-15 16:00
Fixed in latest EAP release 2016.1.2 RC (build 145.969.6)

**Closed by etanshaul** 2016-04-15 16:00 UTC
Labels: App Engine, bug
