### ISSUE TITLE
Closing and returning to a cloud debug session with a breakpoint that has been hit results in a duplicate 'open' breakpoint

### ISSUE THREAD

**Issue by patflynn** [GoogleCloudPlatform/gcloud-intellij#142] opened 2015-10-20 13:21 UTC
steps to reproduce:
1) Start a cloud debug session based off of this doc https://docs.google.com/document/d/1cM1m6yHask_xnZ2E-L0gjo98aPbOWziFnwiK_ZKxzTw/edit#
2) Set a watchpoint
3) Click the red square and end your cloud debug session
4) Select Continue in the dialog that pops up
5) Trigger http://cloud-debugger-demo.appspot.com/gen
6) notice that you will be notified with a link to resume your session
7) note that your captured watchpoint is there, but also a duplicate of that watchpoint in un-hit state has been added.

expected outcome:
Only one watchpoint snapshot is displayed and it's in disabled state

**Comment by elharo** [comment] 2015-12-10 16:04
I think what you're asking is that the Pending snapshot not show up here:

![image](https://cloud.githubusercontent.com/assets/1005544/11720577/c720a118-9f2d-11e5-8bc8-bf6b2180b4b2.png)

**Comment by patflynn** [comment] 2015-12-10 16:06
Correct, the user has not reset the snapshot. I don't know why a pending snapshot has been created.

**Comment by elharo** [comment] 2015-12-10 16:11
FYI, I don't always receive snapshots in the background. In fact, more often than not I don't see them. Not sure why.

**Comment by patflynn** [comment] 2015-12-10 16:12
That sounds like a bug.  It worked for me previously.

**Comment by elharo** [comment] 2015-12-10 18:58
This is a bit of a mess because the GUI is wrapped up pretty tightly with the model code. However, I think the relevant code is in CloudDebugHistoricalSnapshots.MyModel

A snapshot (a.k.a. breakpoint) is pending if breakpoint.getIsFinalState() returns false. 

It could be that the code in the MyModel constrcutor is buggy, or it could be that we're passing a null oldModel into the MyModel constructor when we resume the session, which would explain why the new session doesn't remove the ones from the old session.

**Comment by joaoandremartins** [comment] 2015-12-14 07:42
@patflynn since I can't reproduce #249, thinking about giving this one a go too. Unless anyone else wants to get this out of the way quickly?

**Comment by elharo** [comment] 2015-12-14 11:10
This one should be easier after we merge https://github.com/GoogleCloudPlatform/gcloud-intellij/pull/310

If you review that, I can merge it quickly.

**Comment by patflynn** [comment] 2015-12-14 15:58
I wonder if this bug is related to the #311 that @loosebazooka just reported.

**Comment by patflynn** [comment] 2016-01-06 18:17
@loosebazooka @elharo do you guys know if this bug still exists?

**Comment by joaoandremartins** [comment] 2016-01-07 20:44
I'm still getting this bug. I'm also getting it when I choose Stop Listening instead of Continue.

I think I figured it out. First, a breakpoint is created in the server. Then, you close the session and hit it by calling the servlet. When you resume the session, the server sends over the hit breakpoint, but it doesn't seem to recognise that it is the same one as the open one (the breakpoint is hit offline and it's never disabled/marked as final in IJ, so it is still active when the session is resumed), and another breakpoint set request is triggered on session resume.

**Closed** 2016-01-11 23:09 UTC
Labels: bug, cdb, DI Q4 PE Fixit, help wanted, high priority
