### ISSUE TITLE
Memory leak whenever a flex deployment dialog is displayed

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-intellij#550] opened 2016-03-28 22:28 UTC
For example, if the dialog is displayed three times, the console will report the following error message three times. This only happens when our flex deployment dialog is displayed.

[  38953]  ERROR - api.util.objectTree.ObjectTree - Memory leak detected: com.intellij.openapi.options.SettingsEditorGroup@229a36c0 of class class com.intellij.openapi.options.SettingsEditorGroup

**Comment by etanshaul** [comment] 2016-03-31 16:00
This is an IntelliJ 15.0.3 issue. I tested opening the deploy dialog for other out of the box 3rd party clouds and consistently reproduce the memory leak. The problem is fixed in 2016.1 so there is no point reporting any issue to JetBrains.

**Closed** 2016-03-31 16:26 UTC
Labels: App Engine, low priority
