### ISSUE TITLE
Login service cast exception

### ISSUE THREAD

**Issue by etanshaul** [GoogleCloudPlatform/gcloud-intellij#676] opened 2016-05-12 17:36 UTC
investigate:

Description:
com.google.cloud.tools.intellij.login.IntellijGoogleLoginService cannot be cast to com.google.cloud.tools.intellij.login.GoogleLoginService

Device Model:
unknown

Device Release:
2016.1.2

App Version:
2016.1.2

Category Id:
8590668228
Product Specific Data (whitelisted):
app.name.version: IntelliJ IDEA
app.version.major: 2016
app.version.minor: 1.2
java.version: 1.8.0_76-release
java.vm.vendor: Oracle Corporation
os.name: Linux
plugin.version: 0.9.4-beta

Stack trace:
java.lang.ClassCastException: com.google.cloud.tools.intellij.login.IntellijGoogleLoginService cannot be cast to com.google.cloud.tools.intellij.login.GoogleLoginService
	at com.google.cloud.tools.intellij.login.Services.getLoginService(Services.java:28)
	at com.google.cloud.tools.intellij.elysium.ProjectSelector.needsToSignIn(ProjectSelector.java:293)
	at com.google.cloud.tools.intellij.elysium.ProjectSelector.synchronize(ProjectSelector.java:304)
	at com.google.cloud.tools.intellij.elysium.ProjectSelector.access$300(ProjectSelector.java:75)
	at com.google.cloud.tools.intellij.elysium.ProjectSelector$3$1.run(ProjectSelector.java:168)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Throw file name: Services.java
Throw line number: 28
Throw class name: com.google.cloud.tools.intellij.login.Services
Throw method name: getLoginService

**Comment by chanseokoh** [comment] 2016-05-12 17:40
This was triggered by me. I don't know why it happened. I once logged in yesterday, and have not done anything related to login since then.

**Comment by etanshaul** [comment] 2016-05-12 17:45
I wonder if its related to the new 2016.1.2 version. Either way, we should investigate.

**Comment by chanseokoh** [comment] 2016-05-13 18:18
I think we can basically ignore this error. This will probably happen even on an IDE where our plugin is not installed.

It happens when you open our codebase and open `AppEngineDeploymentRunConfigurationEditor.form` in the GUI Designer. The culprit is the `ProjectSelector` being embedded in our form. Something seems to happen when the GUI Designer tries to draw our custom combo box. The Designer actually runs our code.

**Comment by etanshaul** [comment] 2016-05-13 18:20
Wow that's super weird man.

**Comment by chanseokoh** [comment] 2016-05-13 18:25
Right, so it's possible for a hacker to run an arbitrary code in a user's local machine this way.

**Comment by chanseokoh** [comment] 2016-05-27 16:09
Let's close this. As explained, it's not a bug of our plugin.

**Closed by chanseokoh** 2016-05-27 16:09 UTC
Labels: bug, google-account-plugin
