### ISSUE TITLE
Undeploy doesn't work

### ISSUE THREAD

**Issue by chanseokoh** [GoogleCloudPlatform/gcloud-intellij#702] opened 2016-05-26 03:43 UTC
Just tried undeploying an app right after successful deployment. It completed immediately, but the app was in fact not stopped.

**Comment by chanseokoh** [comment] 2016-05-26 15:38
Strange...

I got this problem when I testing things at home on my external and personal project. As I said, undeploy seemed successful although it actually wasn't.

So, I just tried this at office. No problem when I deploy/undeploy to an internal project. When I tried on to my external project, deploy works fine but undeploy fails with permission denied:

> ERROR: (gcloud.preview.app.versions.stop) Error Response: [403] Operation not allowed
> 
> Details: [
>   [
>     {
>       "@type": "type.googleapis.com/google.rpc.ResourceInfo",
>       "description": "The \"appengine.services.list\" permission is required.",
>       "resourceType": "gae.api"
>     },
>     {
>       "@type": "type.googleapis.com/google.rpc.DebugInfo",
>       "detail": "[ORIGINAL ERROR] generic::permission_denied: Operation not allowed [google.rpc.error_details_ext] { code: 7 message: \"Operation not allowed\" details { type_url: \"type.googleapis.com/google.rpc.ResourceInfo\" value: \"\\n\\007gae.api\\\"5The \\\"appengine.services.list\\\" permission is required.\" } }"
>     }
>   ]
> ]
> 
> Failed to undeploy 'Filesystem JAR or WAR file - target-new.war': Stop application failed with exit code: 1

I will do some more tests, since I just noticed some strange bug of gcloud itself which doesn't make sense at all.

**Comment by etanshaul** [comment] 2016-05-26 15:46
What was the bug that you noticed? Is it related to this?

**Comment by chanseokoh** [comment] 2016-05-26 15:51
Seems somewhat related... I think I found another bug here by accident. It may be the case that the undeploy action isn't using the login credential from our plugin but the credential from the gcloud. The internal bug 28977605 can explain the permission denied error.

**Comment by etanshaul** [comment] 2016-05-26 16:00
If that were the case, couldn't we reproduce this with an internal account too? I.e. make sure you're logged out of gcloud and attempt to undeploy using the IDE.

**Comment by chanseokoh** [comment] 2016-05-26 16:06
Indeed. I tried logging out on the console. Didn't do anything on the IDE. Undeploy gives me the same permission error. Then I tried logging into my personal account on the console. I set the default project to an arbitrary string on the console. It gave me the same error. I set the project to a correct one. Didn't do anything on the IDE. Then the undeploy worked successfully. It is certain that undeploy is using the gcloud's credential.

**Comment by etanshaul** [comment] 2016-05-26 16:17
Yea nice catch. I just double checked that we are properly staging the credentials for stop. gsutil is also properly set for stop (happens in the base action).

**Comment by chanseokoh** [comment] 2016-05-26 16:22
Maybe it is not the credential, but the stop action is using the default project of gcloud. Giving a `--project` argument to `stop` will probably work?

**Comment by etanshaul** [comment] 2016-05-26 16:29
Oh I understand now. Yea we aren't currently setting a project for the stop command. The common lib currently doesn't support this but I think it should. Looking at the sdk documentation `project` looks to be a global flag (not specific to an individual command). I'll test this out and file a bug on the common lib to support this.

**Comment by loosebazooka** [comment] 2016-05-26 16:37
I think project is a parameter on deploy. But maybe other commands need it?

**Comment by meltsufin** [comment] 2016-05-26 17:32
Etan is correct, project seems to be a parameter for all gcloud commands. However, it probably doesn't apply to *all* commands. @etanshaul can you file a bug against the lib?

**Comment by etanshaul** [comment] 2016-05-26 17:39
Just to confirm for anyone that's confused by this thread: this bug doesn't have anything to do with auth really. Its just a matter of not being able to force the project for a given command (other than deploy) and override the default project configured in the cli.

I'll open a bug in the lib.

**Comment by etanshaul** [comment] 2016-05-26 17:42
https://github.com/GoogleCloudPlatform/app-tools-lib-for-java/issues/97

**Comment by etanshaul** [comment] 2016-06-08 22:24
closed via #714

**Closed by etanshaul** 2016-06-08 22:24 UTC
Labels: App Engine, bug
